"""Daily digest: generate HTML email from Top-N high-match jobs and send.

Following final two steps of n8n workflow:
- Build Email HTML
- Send a message (Gmail)
"""
from __future__ import annotations

import smtplib
from datetime import datetime, timedelta
from email.message import EmailMessage
from pathlib import Path

from sqlalchemy import select

from .config import Config
from .db import Job, JobStatus, session_scope


def top_jobs(config: Config, top_n: int) -> list[Job]:
    """Get recently scored high-score jobs."""
    db_path = config.path("db_path")
    cutoff = datetime.utcnow() - timedelta(days=2)
    with session_scope(db_path) as session:
        stmt = (
            select(Job)
            .where(
                Job.status.in_([JobStatus.SCORED.value, JobStatus.SHORTLISTED.value]),
                Job.match_score.is_not(None),
                Job.updated_at >= cutoff,
            )
            .order_by(Job.match_score.desc())
            .limit(top_n)
        )
        # Detach so caller can use after session close
        jobs = list(session.scalars(stmt).all())
        for j in jobs:
            session.expunge(j)
        return jobs


def build_html(jobs: list[Job], min_recommend: float) -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    rows = []
    for j in jobs:
        score = j.match_score or 0
        color = "#16a34a" if score >= 80 else ("#ca8a04" if score >= 65 else "#6b7280")
        strengths = (j.match_strengths or "").replace("\n", "<br>")
        gaps = (j.match_gaps or "").replace("\n", "<br>")
        rows.append(f"""
        <tr>
          <td style="padding:12px;border-bottom:1px solid #e5e7eb;vertical-align:top">
            <div style="font-size:24px;font-weight:700;color:{color}">{score:.0f}</div>
          </td>
          <td style="padding:12px;border-bottom:1px solid #e5e7eb">
            <div style="font-size:16px;font-weight:600">
              <a href="{j.url}" style="color:#1f2937;text-decoration:none">{_esc(j.title)}</a>
            </div>
            <div style="color:#6b7280;font-size:14px;margin-top:2px">
              {_esc(j.company)} &middot; {_esc(j.location or '')} &middot;
              <span style="text-transform:uppercase;font-size:11px">{j.source}</span>
            </div>
            <div style="margin-top:8px;color:#374151;font-size:14px">
              {_esc(j.match_summary or '')}
            </div>
            <div style="margin-top:8px;font-size:13px;color:#16a34a">
              <b>Strengths:</b><br>{strengths}
            </div>
            <div style="margin-top:6px;font-size:13px;color:#dc2626">
              <b>Gaps:</b><br>{gaps}
            </div>
          </td>
        </tr>
        """)

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;background:#f9fafb;padding:20px">
  <div style="max-width:720px;margin:0 auto;background:white;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1)">
    <div style="background:#111827;color:white;padding:20px">
      <div style="font-size:20px;font-weight:600">Daily JobHunter Digest</div>
      <div style="color:#9ca3af;font-size:13px;margin-top:4px">{today} &middot; Top {len(jobs)} &middot; Recommendation threshold {min_recommend:.0f}</div>
    </div>
    <table style="width:100%;border-collapse:collapse">
      {''.join(rows) if rows else '<tr><td style="padding:30px;text-align:center;color:#6b7280">No new matching jobs today 🎉</td></tr>'}
    </table>
    <div style="padding:16px;background:#f9fafb;color:#6b7280;font-size:12px;text-align:center">
      Auto-generated by JobHunter · Reply archive #&lt;id&gt; to skip a job
    </div>
  </div>
</body></html>"""
    return html


def _esc(s: str) -> str:
    return (
        (s or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def send_email(config: Config, html: str, subject: str | None = None) -> bool:
    """Send email via SMTP. Return False on failure (no exception, digest failure shouldn't block main pipeline)."""
    cfg = config.digest
    to = cfg.get("to")
    if not to:
        print("[digest] Recipient email not configured, skipping send")
        return False
    smtp_cfg = cfg.get("smtp", {})
    host = smtp_cfg.get("host")
    port = int(smtp_cfg.get("port", 587))
    username = smtp_cfg.get("username")
    password_env = smtp_cfg.get("password_env", "SMTP_PASSWORD")
    password = config.env(password_env)
    if not (host and username and password):
        print(f"[digest] SMTP not fully configured (need username + {password_env}), skipping send")
        return False

    msg = EmailMessage()
    msg["Subject"] = subject or f"Daily JobHunter Digest - {datetime.now():%Y-%m-%d}"
    msg["From"] = username
    msg["To"] = to
    msg.set_content("This email requires HTML view mode")
    msg.add_alternative(html, subtype="html")

    try:
        with smtplib.SMTP(host, port) as s:
            s.starttls()
            s.login(username, password)
            s.send_message(msg)
        print(f"[digest] Sent to {to}")
        return True
    except Exception as e:
        print(f"[digest] Email send failed: {e}")
        return False


def run_digest(config: Config) -> Path:
    """Generate HTML digest, optionally send email, save HTML file to outputs/."""
    cfg = config.digest
    top_n = int(cfg.get("top_n", 15))
    min_recommend = float(config.scoring.get("min_recommend_score", 70))

    jobs = top_jobs(config, top_n)
    html = build_html(jobs, min_recommend)

    outputs_dir = config.path("outputs_dir")
    out_path = outputs_dir / f"digest_{datetime.now():%Y%m%d}.html"
    out_path.write_text(html, encoding="utf-8")
    print(f"[digest] HTML generated: {out_path}")

    if cfg.get("enabled", False):
        send_email(config, html)

    return out_path
